apiVersion: apaarshrm.dev/v1alpha1
kind: Kluster
metadata:
  name: kluster-1
  namespace: default
spec:
  name: kluster-1
  region: "nyc1"
  version: "1.21.5-do.0"
  secretToken: "default/dosecret"
  nodepool: 
  - count: 1
    name: "frontend-pool"
    size: "s-2vcpu-2gb"